from enum import Enum


class NodeLabels(Enum):
    FOLDER = "FOLDER"
    FILE = "FILE"
    FUNCTION = "FUNCTION"
    CLASS = "CLASS"
    METHOD = "METHOD"
    MODULE = "MODULE"
    DELETED = "DELETED"
    DESCRIPTION = "DESCRIPTION"
    FILESYSTEM = "FILESYSTEM"
    FILESYSTEM_FILE = "FILESYSTEM_FILE"
    FILESYSTEM_DIRECTORY = "FILESYSTEM_DIRECTORY"
    DOCUMENTATION_FILE = "DOCUMENTATION_FILE"
    CONCEPT = "CONCEPT"
    DOCUMENTED_ENTITY = "DOCUMENTED_ENTITY"
    DOCUMENTATION_SECTION = "DOCUMENTATION_SECTION"
