from enum import Enum


class RelationshipType(Enum):
    # Code hierarchy
    CONTAINS = "CONTAINS"
    FUNCTION_DEFINITION = "FUNCTION_DEFINITION"
    CLASS_DEFINITION = "CLASS_DEFINITION"

    # Code references
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    INHERITS = "INHERITS"
    INSTANTIATES = "INSTANTIATES"
    TYPES = "TYPES"
    ASSIGNS = "ASSIGNS"
    USES = "USES"

    # Code diff
    MODIFIED = "MODIFIED"
    DELETED = "DELETED"
    ADDED = "ADDED"
    
    # LLM descriptions
    HAS_DESCRIPTION = "HAS_DESCRIPTION"
    REFERENCES_IN_DESCRIPTION = "REFERENCES_IN_DESCRIPTION"
    
    # Filesystem relationships
    IMPLEMENTS = "IMPLEMENTS"
    DEPENDS_ON = "DEPENDS_ON"
    FILESYSTEM_CONTAINS = "FILESYSTEM_CONTAINS"
    REFERENCED_BY_DESCRIPTION = "REFERENCED_BY_DESCRIPTION"
    
    # Documentation relationships
    CONTAINS_CONCEPT = "CONTAINS_CONCEPT"
    DESCRIBES_ENTITY = "DESCRIBES_ENTITY"
    RELATES_TO = "RELATES_TO"
    DOCUMENTS = "DOCUMENTS"
    IMPLEMENTS_CONCEPT = "IMPLEMENTS_CONCEPT"
